# Generated by Django 4.1.5 on 2023-02-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aContext", "0007_alter_context_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgeType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "EdgeType",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="NodeType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "NodeType",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="aContext.context",
                    ),
                ),
                (
                    "nType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="aNode.nodetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Node",
                "ordering": ("context_id", "nType", "name"),
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "eType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="aNode.edgetype",
                    ),
                ),
                (
                    "fromNode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fromNode",
                        to="aNode.node",
                    ),
                ),
                (
                    "toNode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toNode",
                        to="aNode.node",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Edge",
                "ordering": ("fromNode", "toNode", "eType"),
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["context_id", "nType", "name"],
                name="aNode_node_context_e4ea33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["name", "nType", "context_id"],
                name="aNode_node_name_df75ef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("context_id", "nType", "name")},
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["fromNode", "toNode", "eType"],
                name="aNode_edge_fromNod_5a292e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["toNode", "fromNode", "eType"],
                name="aNode_edge_toNode__83eb45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["eType", "fromNode", "toNode"],
                name="aNode_edge_eType_i_5e7f44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["eType", "toNode", "fromNode"],
                name="aNode_edge_eType_i_c65900_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together={("fromNode", "toNode", "eType")},
        ),
    ]
