# Generated by Django 4.1.6 on 2023-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aNode", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={"ordering": ("nType", "name"), "verbose_name_plural": "Node"},
        ),
        migrations.RemoveIndex(
            model_name="node",
            name="aNode_node_context_e4ea33_idx",
        ),
        migrations.RemoveIndex(
            model_name="node",
            name="aNode_node_name_df75ef_idx",
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("nType", "name")},
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["nType", "name"], name="aNode_node_nType_i_e64919_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["name", "nType"], name="aNode_node_name_b14e13_idx"),
        ),
        migrations.RemoveField(
            model_name="node",
            name="context",
        ),
    ]
