# Generated by Django 4.1.6 on 2023-02-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aNode", "0002_alter_node_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={
                "ordering": ("parent", "nType", "name"),
                "verbose_name_plural": "Node",
            },
        ),
        migrations.RemoveIndex(
            model_name="node",
            name="aNode_node_nType_i_e64919_idx",
        ),
        migrations.RemoveIndex(
            model_name="node",
            name="aNode_node_name_b14e13_idx",
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="node",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parentNode",
                to="aNode.node",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="node",
            unique_together={("parent", "nType", "name")},
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["parent", "nType", "name"], name="aNode_node_parent__c4b8d7_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["name", "nType", "parent"], name="aNode_node_name_c83cff_idx"),
        ),
    ]
