# Generated by Django 4.1.6 on 2023-02-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aNode", "0003_alter_node_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={
                "ordering": ("parent_id", "nType", "name"),
                "verbose_name_plural": "Node",
            },
        ),
    ]
