# Generated by Django 4.1.6 on 2023-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aNode", "0004_alter_node_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="payLoad",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="payLoad",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
