# Generated by Django 4.1.6 on 2023-03-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aNode", "0006_alter_node_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="eType",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aNode.edgetype"),
        ),
        migrations.AlterField(
            model_name="node",
            name="nType",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aNode.nodetype"),
        ),
        migrations.AlterField(
            model_name="node",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parentNode",
                to="aNode.node",
            ),
        ),
    ]
