# Generated by Django 4.1.6 on 2023-02-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aContext", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="context",
            options={"verbose_name_plural": "Context"},
        ),
    ]
