# Generated by Django 4.1.6 on 2023-02-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aContext", "0003_alter_context_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="aContext.context",
            ),
        ),
    ]
