# Generated by Django 4.1.6 on 2023-02-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aContext", "0006_alter_context_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="context",
            options={
                "ordering": ("parent_id", "name"),
                "verbose_name_plural": "Context",
            },
        ),
    ]
