# Generated by Django 4.1.6 on 2023-02-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creStamp", models.DateTimeField(auto_now_add=True)),
                ("updStamp", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="aMain.context"),
                ),
            ],
            options={
                "verbose_name_plural": "Context",
                "ordering": ("parent", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="context",
            index=models.Index(fields=["parent", "name"], name="aMain_conte_parent__c30603_idx"),
        ),
        migrations.AddIndex(
            model_name="context",
            index=models.Index(fields=["name", "parent"], name="aMain_conte_name_ea4ad7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="context",
            unique_together={("parent", "name")},
        ),
    ]
