# Generated by Django 4.1.6 on 2023-02-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aMain", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Context",
        ),
    ]
